# Generated by Django 5.0.4 on 2024-11-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_delete_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.png", upload_to="profile_pics/"
            ),
        ),
    ]
