# Generated by Django 5.0.4 on 2024-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_phone_profile_sex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="sex",
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
