# Generated by Django 5.0.4 on 2024-11-19 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_profile_sex_alter_profile_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
    ]
